# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: 3tgqLEed
    url: /#top
    weight: 10
  - name: Research
    identifier: x6K-TIvi
    url: /#research
    weight: 20
  - name: Team
    identifier: eHBLnfuQ
    url: /#team
    weight: 30
  - name: Contact
    identifier: eM2nHS6I
    url: /#contact
    weight: 40
